import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import {connectDb} from "@/config/db.js"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDb()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar sideMenu={true} />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
